name: Build and Release Windows Forms App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --configuration Release

    - name: Publish as single executable
      run: |
        dotnet publish `
          --configuration Release `
          --output ./publish `
          --runtime win-x64 `
          --self-contained true `
          -p:PublishSingleFile=true `
          -p:PublishTrimmed=true `
          -p:IncludeNativeLibrariesForSelfExtract=true

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v1.0.${{ github.run_number }}
        name: Fractalii Release v1.0.${{ github.run_number }}
        body: |
          Automated release of the Fractalii Windows Forms app.
          Download the .exe file below and run it on Windows.
        files: ./publish/*.exe