name: Build and Release Windows Forms App

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Publish as standalone executable
      run: |
        dotnet publish Fractalii.csproj `
          --configuration Release `
          --output ./publish `
          --runtime win-x64 `
          --self-contained true `
          -p:PublishSingleFile=true `
          -p:IncludeNativeLibrariesForSelfExtract=true `
          -p:GenerateAssemblyVersionInfo=false

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ github.run_number }}
        name: Fractalii Release v${{ github.run_number }}
        body: |
          Standalone executable for Fractalii.
          Just download and run the .exe file.
        files: ./publish/*.exe